### ISSUE TITLE
Create initial asp.net project

### ISSUE THREAD

**Issue by JaredLGillespie** [SprinkleLord/card-inventory-backend#2]
_Initial creation of ASP.NET project._
- scaffold [ASP.NET CORE rest api](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) solutio
- create readme.md with development requirements / info
- .gitignore, testing project ([MS Test](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest), [Autofixture](https://github.com/AutoFixture/AutoFixture), [NSubstitute](http://nsubstitute.github.io/)), etc.

**Comment by Shyam-Patel** [comment]
This is finished. Created a ASP.NET Core Web API project.
