### ISSUE TITLE
Setup azure hosting / account creation

### ISSUE THREAD

**Issue by JaredLGillespie** [SprinkleLord/card-inventory-backend#6]
- Create azure account
- Create sql database (will need connection strings)
- Setup back end project deployment to azure 
- Setup front end project deployment to azure

**Comment by JaredLGillespie** [comment]
The DB and back end appear to be done. The front end should also be added as well though.

**Comment by Shyam-Patel** [comment]
Everything's hosted and good to go on Azure.
